service:
  name: service-telemetry-docs
  namespace: aicares
image:
  repository: 952893849914.dkr.ecr.us-east-1.amazonaws.com/aicares-application/telemetry-docs
  tag: latest
  pullPolicy: Always
containerPort: 8000
resources:
  limits:
    memory: "100Mi"
  requests:
    memory: "32Mi"
    cpu: "50m"
env:
  - name: OTEL_SERVICE_NAME
    value: "telemetry-docs"
  - name: OTEL_COLLECTOR_HOST
    value: "otel-collector"
  - name: OTEL_COLLECTOR_PORT_GRPC
    value: "4317"
  - name: TELEMETRY_DOCS_PORT
    value: "8000"
nodeSelector:
  eks.amazonaws.com/nodegroup: graviton-workers
